language: node_js
env:
  - CXX=g++-4.8 BABEL_CACHE_PATH=$HOME/.babel-cache/cache
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
  postgresql: "9.4"
node_js:
  - "4.1"
  - "4.0"
before_script:
  - npm prune --production=false
  - cp test/config.travis.json test/config.json
after_script:
  - npm install -g eclint
  - npm run eclint
  - npm install -g eslint
  - npm run eslint
  - npm run coveralls
services:
  - postgresql
cache:
  directories:
    - $HOME/.npm
    - node_modules
    - $HOME/.babel-cache
    - $HOME/.nvm
    - $NVM_DIR
sudo: false
