language: node_js
env:
  - CXX=g++-4.8
  - BABEL_CACHE_PATH=$HOME/.babel-cache
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
  postgresql: "9.3"
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
before_script:
  - npm update --dev
  - npm prune --production=false
  - npm install -g eclint
  - npm run eclint
  - npm install -g eslint
  - npm run eslint
  - cp test/config.travis.json test/config.json
services:
  - postgresql
cache:
  directories:
    - $HOME/.npm
    - node_modules
    - $BABEL_CACHE_PATH
sudo: false
