language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
before_script:
  - npm install -g eclint
  - npm run eclint
  - npm install -g eslint
  - npm run eslint
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
